site_name: Terrafom Framework Validators

theme:
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
  features:
    - navigation.sections
    - navigation.top
    - content.code.annotate
    - header.autohide
  icon:
    repo: fontawesome/brands/github-alt

nav:
  - Overview: "index.md"
  - Getting Started: "getting-started.md"
  - Validators:
      - String: "stringvalidator/index.md"
      - Bool: "boolvalidator/index.md"
      - Int64: "int64validator/index.md"
      - List: "listvalidator/index.md"
      - Set: "setvalidator/index.md"
      - Map: "mapvalidator/index.md"
  - FrangipaneTeam:
      - About: "https://team.frangipane.io/"
      - GitHub: "https://github.com/FrangipaneTeam"
  - Other projects:
      - PlanModifiers: "https://team.frangipane.io/terraform-plugin-framework-planmodifiers/"


plugins:
  - search

markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list

repo_url: https://github.com/FrangipaneTeam/terraform-plugin-framework-validators
repo_name: FrangipaneTeam/terraform-plugin-framework-validators