site_name: Terrafom Framework Validators

theme:
  name: material
  palette:
    - scheme: orangeCorp

  features:
    - navigation.sections
    - navigation.top
    - content.code.annotate
    - header.autohide
  icon:
    repo: fontawesome/brands/github-alt
  favicon: images/favicon.png
  logo: images/logo.png

extra_css:
  - stylesheets/extra.css

nav:
  - How to use: "getting-started.md"
  - String: "stringvalidator/index.md"
  - Bool: "boolvalidator/index.md"
  - Int64: "int64validator/index.md"
  - List: "listvalidator/index.md"
  - Set: "setvalidator/index.md"
  - Map: "mapvalidator/index.md"

plugins:
  - search

markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list

repo_url: https://github.com/FrangipaneTeam/terraform-plugin-framework-validators
repo_name: FrangipaneTeam/terraform-plugin-framework-validators